// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Mangaedb.Model
{
    [Table("categoria")]
    public partial class Categoria
    {
        public Categoria()
        {
            CategoriaManga = new HashSet<CategoriaManga>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(30)]
        [Unicode(false)]
        public string Nome { get; set; }

        [InverseProperty("IdCategoriaNavigation")]
        public virtual ICollection<CategoriaManga> CategoriaManga { get; set; }

        public override string ToString()
        {
            return Nome;
        }
    }
}