// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Mangaedb.Model
{
    [Table("comentario")]
    public partial class Comentario
    {
        public Comentario()
        {
            CurtidaComentario = new HashSet<CurtidaComentario>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("id_manga")]
        public int IdManga { get; set; }
        [Column("id_usuario")]
        public int IdUsuario { get; set; }
        [Required]
        [Column("conteudo")]
        [StringLength(280)]
        [Unicode(false)]
        public string Conteudo { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }

        [ForeignKey("IdManga")]
        [InverseProperty("Comentario")]
        public virtual Manga IdMangaNavigation { get; set; }
        [ForeignKey("IdUsuario")]
        [InverseProperty("Comentario")]
        public virtual Usuario IdUsuarioNavigation { get; set; }
        [InverseProperty("IdComentarioNavigation")]
        public virtual ICollection<CurtidaComentario> CurtidaComentario { get; set; }
    }
}