// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Mangaedb.Model
{
    [Table("curtida_manga")]
    public partial class CurtidaManga
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("id_manga")]
        public int IdManga { get; set; }
        [Column("id_usuario")]
        public int IdUsuario { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }
        [Column("deleted_at", TypeName = "datetime")]
        public DateTime? DeletedAt { get; set; }

        [ForeignKey("IdManga")]
        [InverseProperty("CurtidaManga")]
        public virtual Manga IdMangaNavigation { get; set; }
        [ForeignKey("IdUsuario")]
        [InverseProperty("CurtidaManga")]
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}