// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Mangaedb.Model
{
    [Table("curtida_comentario")]
    public partial class CurtidaComentario
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("id_comentario")]
        public int IdComentario { get; set; }
        [Column("id_usuario")]
        public int IdUsuario { get; set; }
        [Column("valor_curtida")]
        public byte ValorCurtida { get; set; }

        [ForeignKey("IdComentario")]
        [InverseProperty("CurtidaComentario")]
        public virtual Comentario IdComentarioNavigation { get; set; }
        [ForeignKey("IdUsuario")]
        [InverseProperty("CurtidaComentario")]
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}