// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Mangaedb.Model
{
    public partial class MangaedbContext : DbContext
    {
        public MangaedbContext()
        {
        }

        public MangaedbContext(DbContextOptions<MangaedbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CategoriaManga> CategoriaManga { get; set; }
        public virtual DbSet<Manga> Manga { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                // warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-FOTF1HF\\SQLEXPRESS;Initial Catalog=mangaedb;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CategoriaManga>(entity =>
            {
                entity.HasOne(d => d.IdCategoriaNavigation)
                    .WithMany(p => p.CategoriaManga)
                    .HasForeignKey(d => d.IdCategoria)
                    .HasConstraintName("FK_categoria_manga_categoria");

                entity.HasOne(d => d.IdMangaNavigation)
                    .WithMany(p => p.CategoriaManga)
                    .HasForeignKey(d => d.IdManga)
                    .HasConstraintName("FK_categoria_manga_manga");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}