// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Mangaedb.Model
{
    [Table("manga")]
    public partial class Manga
    {
        public Manga()
        {
            CategoriaManga = new HashSet<CategoriaManga>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(100)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("sinopse", TypeName = "text")]
        public string Sinopse { get; set; }

        [Display(Name = "Categoria")]
        [InverseProperty("IdMangaNavigation")]
        public virtual ICollection<CategoriaManga> CategoriaManga { get; set; }
    }
}