// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Mangaedb.Model
{
    [Table("usuario")]
    public partial class Usuario
    {
        public Usuario()
        {
            Comentario = new HashSet<Comentario>();
            CurtidaComentario = new HashSet<CurtidaComentario>();
            CurtidaManga = new HashSet<CurtidaManga>();
            IdManga = new HashSet<Manga>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(15)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("email")]
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("senha")]
        [StringLength(50)]
        [Unicode(false)]
        public string Senha { get; set; }
        [Column("ativo")]
        public bool Ativo { get; set; }

        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<CurtidaComentario> CurtidaComentario { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<CurtidaManga> CurtidaManga { get; set; }

        [ForeignKey("IdUsuario")]
        [InverseProperty("IdUsuario")]
        public virtual ICollection<Manga> IdManga { get; set; }
    }
}